// MISSION CONTROL — cached data feed
// Generated by the dashboard-refresh probe. Every number below came from a live
// tool call at generatedAt; sources that failed or required auth are marked
// offline/auth and their panels render a NO SIGNAL state instead of fake data.
window.MISSION_DATA = {
  generatedAt: "2026-08-10T19:10:00Z",
  operator: {
    name: "Mona Jackson-Ham",
    email: "mjunlimitedessentials@gmail.com",
    org: "MJUnlimited Essential Marketing · ThinkBox AI Operation Systems",
    timezone: "America/New_York"
  },

  briefing: {
    headline: "Bootcamp Day 1 is tonight at 5 — and your Canva board lit up with a second ticket concept ('Beyond the Stars', two versions) while Gmail sits dark a fifth probe.",
    actions: [
      {
        priority: 1,
        title: "Tonight 5–7 PM: Claude Code Bootcamp Day 1",
        detail: "Vibe Coding Incubator, Zoom webinar link from your inbox. If the pre-work at portal.vcinc.ai isn't done, the 3–5 PM window is the last chance. Circle follows at 8 — a double evening, repeated nightly through Thursday.",
        sources: ["Google Calendar"]
      },
      {
        priority: 2,
        title: "New event brewing? 'Beyond the Stars' tickets landed in Canva",
        detail: "Two versions of a Pink/Black/White 'Beyond the Stars' ticket plus one untitled design were created in the last day, following the Blue/White Conference Ticket from Aug 7. If a paid event is forming, the proven Jotform registration flow ($175 test on Aug 1) is ready to wire up.",
        sources: ["Canva"]
      },
      {
        priority: 3,
        title: "Gmail dark a 5th probe — a full week of email blindness",
        detail: "No email intel since Mon Aug 3: payment-retry results from the 7 other dead-card vendors, Intensive replies, and bootcamp confirmations are all invisible to the dashboard. Fix: claude.ai → Settings → Connectors → reconnect Gmail, then say 'refresh'.",
        sources: ["Gmail"]
      },
      {
        priority: 4,
        title: "Slack silent day 18 — send the replay + invite in one email",
        detail: "#all-thinkbox-ai-operating-systems still has zero messages two days after the Intensive. One email to attendees — replay link + capstone + direct Slack invite — turns students into the channel's first signal.",
        sources: ["Slack"]
      },
      {
        priority: 5,
        title: "Higgsfield steady at 1,618.41 — fuel parked and paid for",
        detail: "No credit burn since Sunday morning; the renewed Ultimate plan is stable. The media-kit promo video remains the highest-value use of that balance once bootcamp week settles.",
        sources: ["Higgsfield"],
        money: true
      },
      {
        priority: 6,
        title: "Thursday is the crunch point of the week",
        detail: "AI4B Fail Forward 3–4 PM rolls straight into Bootcamp Day 4 at 5, then Circle at 8 — three commitments back-to-back. Protect the afternoon; nothing else books on Thursday.",
        sources: ["Google Calendar"]
      },
      {
        priority: 7,
        title: "PRO Welcome duplicate hit week 6 today — and week 7 is queued",
        detail: "Today's 1 PM call was listed twice again, and next Monday already shows the same double. Two minutes in Google Calendar deletes the duplicate recurring series for good.",
        sources: ["Google Calendar"]
      },
      {
        priority: 8,
        title: "Notion: give bootcamp week a notes page",
        detail: "You kept 'Today's Notes! AI Agents Bootcamps' pages for the May bootcamp — same move tonight would end the 4-week edit drought and capture the Claude Code material while it's live.",
        sources: ["Notion"]
      }
    ]
  },

  // Connector status board — probed live. never guess: online = returned data,
  // offline = call blocked/failed in this environment, auth = needs authorization.
  sources: [
    { name: "Gmail",           status: "offline", detail: "approval blocked — 5th probe in a row" },
    { name: "Google Calendar", status: "online",  detail: "7-day window queried, ET" },
    { name: "Notion",          status: "online",  detail: "workspace search OK" },
    { name: "Slack",           status: "online",  detail: "thinkboxaiope workspace" },
    { name: "Canva",           status: "online",  detail: "3 new designs since yesterday" },
    { name: "Higgsfield",      status: "online",  detail: "1,618.41 credits — Ultimate stable" },
    { name: "Google Drive",    status: "offline", detail: "approval pending — blocked on recent runs" },
    { name: "Stripe",          status: "offline", detail: "needs authorization — reports in inbox" },
    { name: "Granola",         status: "offline", detail: "call requires approval" },
    { name: "Zoom",            status: "offline", detail: "call requires approval" },
    { name: "Supabase",        status: "offline", detail: "call requires approval" },
    { name: "vidIQ",           status: "offline", detail: "call requires approval" },
    { name: "Gamma",           status: "offline", detail: "call requires approval" },
    { name: "Jotform",         status: "offline", detail: "connector blocked — data via Gmail" },
    { name: "Lovable",         status: "offline", detail: "call requires approval" },
    { name: "Adobe AEM",       status: "offline", detail: "needs authorization" },
    { name: "Unnamed server",  status: "auth",    detail: "needs OAuth re-authorization" }
  ],

  // Gmail probe approval-blocked again this run — panel shows NO SIGNAL.
  gmail: {
    inboxEstimateLast3Days: null,
    unreadShown: null,
    threads: []
  },

  calendar: {
    timezone: "America/New_York",
    calendarCount: 6,
    calendars: ["Personal", "NO NONSENSE WEIGHTLOSS TRAINING", "Family", "Sing Like A Star Challenge", "AI4B PRO", "US Holidays"],
    events: [
      { day: "MON 08/10", time: "5:00 PM", title: "Claude Code Bootcamp — Day 1", loc: "Zoom webinar", note: "TONIGHT — pre-work first" },
      { day: "MON 08/10", time: "8:00 PM", title: "Marqus Beaver Business Circle", loc: "Zoom", note: "double evening" },
      { day: "TUE 08/11", time: "5:00 PM", title: "Claude Code Bootcamp — Day 2", loc: "Zoom webinar", note: "" },
      { day: "WED 08/12", time: "5:00 PM", title: "Claude Code Bootcamp — Day 3", loc: "Zoom webinar", note: "" },
      { day: "THU 08/13", time: "3:00 PM", title: "AI4B Fail Forward → Bootcamp Day 4 (5 PM) → Circle (8 PM)", loc: "Zoom", note: "crunch day — 3 back-to-back" },
      { day: "MON 08/17", time: "1:00 PM", title: "PRO Welcome Call", loc: "Zoom webinar", note: "duplicate ×2 — 7th week queued" }
    ]
  },

  notion: {
    openTasks: 0,
    tasksDb: "My Tasks (assigned to me, To-do + In progress)",
    recentPages: [
      { title: "Day 1 — Attendee Notes!", edited: "2026-07-10" },
      { title: "Day 3 — Attendee notes", edited: "2026-07-10" },
      { title: "Today's Notes! AI Agents Bootcamps", edited: "2026-05-18" },
      { title: "AI Business Summit Notes and Prompts", edited: "2026-05-15" }
    ]
  },

  // Google Drive probe blocked on recent runs — panel shows NO SIGNAL.
  drive: { files: [] },

  canva: {
    designs: [
      { title: "Beyond the Stars Ticket — Pink/Black/White (v1)", updated: "NEW — last 24h" },
      { title: "Beyond the Stars Ticket — Pink/Black/White (v2)", updated: "NEW — last 24h" },
      { title: "Untitled design (1 page)", updated: "NEW — last 24h" },
      { title: "Blue & White Business Conference Ticket (2 pages)", updated: "Aug 7" },
      { title: "ThinkBox training wall chart (AI integration guide)", updated: "Jul 30" },
      { title: "ELICM Website", updated: "recent" }
    ]
  },

  slack: {
    workspace: "thinkboxaiope",
    channels: [
      { name: "#all-thinkbox-ai-operating-systems", messages: 0, purpose: "announcements — day 18 silent" },
      { name: "#social", messages: 0, purpose: "fun / team bonding" }
    ]
  },

  higgsfield: {
    credits: 1618.41,
    plan: "Ultimate"
  }
};
