// MISSION CONTROL — cached data feed
// Generated by the dashboard-refresh probe. Every number below came from a live
// tool call at generatedAt; sources that failed or required auth are marked
// offline/auth and their panels render a NO SIGNAL state instead of fake data.
window.MISSION_DATA = {
  generatedAt: "2026-08-06T11:15:00Z",
  operator: {
    name: "Mona Jackson-Ham",
    email: "mjunlimitedessentials@gmail.com",
    org: "MJUnlimited Essential Marketing · ThinkBox AI Operation Systems",
    timezone: "America/New_York"
  },

  briefing: {
    headline: "You enrolled in a Claude Code Bootcamp overnight — pre-install session TONIGHT at 6 — stacking today into a triple-header, while Saturday's Intensive (2 days out) is still double-listed and Gmail sat out a second probe.",
    actions: [
      {
        priority: 1,
        title: "Tonight is a triple-header — pace the day for it",
        detail: "3:00 PM AI4B Fail Forward (Patrick Precourt) → 6:00–7:30 PM Claude Code Bootcamp Pre-Installation with Kaila (Zoom 831 5260 7635, added at 12:21 AM) → 8:00 PM Circle. If Lori's Impact Scholarship is still on your list, its deadline is today — draft it this morning.",
        sources: ["Google Calendar", "Gmail (Aug 4 probe)"]
      },
      {
        priority: 2,
        title: "Claude Code Bootcamp booked: Mon–Thu next week, 5–7 PM ET",
        detail: "Vibe Coding Incubator workshop runs Aug 10–13. Pre-work required BEFORE Day 1: sign in at portal.vcinc.ai → Learning tab → Claude Code Pre-Work Course; the Zoom webinar link arrived by email from Zoom — bookmark it. This connects to the vcinc.ai '$0.67/day development team' email you starred Aug 1.",
        sources: ["Google Calendar"]
      },
      {
        priority: 3,
        title: "2 days to the ThinkBox Intensive — duplicate STILL on the calendar",
        detail: "Saturday 6–9 PM (Zoom 824 0301 7297) remains listed twice since Jul 25. With registrations presumably arriving, delete one copy today. Kit, Ultra deck, and wall chart are all ready in the repo and Canva.",
        sources: ["Google Calendar", "Canva"]
      },
      {
        priority: 4,
        title: "Gmail dark for a 2nd probe — approve it to restore email intel",
        detail: "The Gmail connector required approval again this morning; its panel stays NO SIGNAL and the card-cascade status is now two cycles stale (8 vendors as of Tuesday). Opening this Claude session and tapping Allow on the pending Gmail permission restores it on the next refresh.",
        sources: ["Gmail"]
      },
      {
        priority: 5,
        title: "Next week is the heaviest on record — protect the evenings",
        detail: "Mon Aug 10 alone: PRO Welcome Call 1 PM (still duplicated ×2, week 6), Bootcamp 5–7 PM, Circle 8 PM. Then Bootcamp every evening through Thursday, plus AI4B Thursday 3 PM. Do the bootcamp pre-work this weekend or it collides with Intensive recovery.",
        sources: ["Google Calendar"]
      },
      {
        priority: 6,
        title: "Higgsfield still active — billing fix window holds",
        detail: "Credits 437.91 and Ultimate plan verified live this morning despite Sunday's 'update payment' email. The renewal will eventually retry — the card update remains the highest-leverage fix (8 vendors as of last Gmail read).",
        sources: ["Higgsfield", "Gmail (Aug 4 probe)"],
        money: true
      },
      {
        priority: 7,
        title: "Carried forward: Naneth (Upwork) and Tresti replies",
        detail: "Both threads were awaiting replies at the last successful Gmail probe (Mon night): Naneth M.'s revived hiring message, and Tresti's 'let me know if you get this' email + 4 Instagram DMs.",
        sources: ["Gmail (Aug 4 probe)"]
      },
      {
        priority: 8,
        title: "Boards silent day 14 — two days to the planned first transmission",
        detail: "Notion unchanged since Jul 10; Slack #all-thinkbox-ai-operating-systems verified empty again. Saturday's Advanced-track capstone posts the channel's first message.",
        sources: ["Notion", "Slack"]
      }
    ]
  },

  // Connector status board — probed live. never guess: online = returned data,
  // offline = call blocked/failed in this environment, auth = needs authorization.
  sources: [
    { name: "Gmail",           status: "offline", detail: "approval blocked — 2nd probe in a row" },
    { name: "Google Calendar", status: "online",  detail: "7-day window queried, ET" },
    { name: "Notion",          status: "online",  detail: "workspace search OK" },
    { name: "Slack",           status: "online",  detail: "thinkboxaiope workspace" },
    { name: "Canva",           status: "online",  detail: "design list OK" },
    { name: "Higgsfield",      status: "online",  detail: "credits + plan OK — billing email pending" },
    { name: "Google Drive",    status: "offline", detail: "approval pending — blocked on recent runs" },
    { name: "Stripe",          status: "offline", detail: "needs authorization — reports in inbox" },
    { name: "Granola",         status: "offline", detail: "call requires approval" },
    { name: "Zoom",            status: "offline", detail: "call requires approval" },
    { name: "Supabase",        status: "offline", detail: "call requires approval" },
    { name: "vidIQ",           status: "offline", detail: "call requires approval" },
    { name: "Gamma",           status: "offline", detail: "call requires approval" },
    { name: "Jotform",         status: "offline", detail: "connector blocked — data via Gmail" },
    { name: "Lovable",         status: "offline", detail: "call requires approval" },
    { name: "Adobe AEM",       status: "offline", detail: "not probed — no env access" },
    { name: "Unnamed server",  status: "auth",    detail: "needs OAuth re-authorization" }
  ],

  // Gmail probe approval-blocked again this run — panel shows NO SIGNAL.
  gmail: {
    inboxEstimateLast3Days: null,
    unreadShown: null,
    threads: []
  },

  calendar: {
    timezone: "America/New_York",
    calendarCount: 6,
    calendars: ["Personal", "NO NONSENSE WEIGHTLOSS TRAINING", "Family", "Sing Like A Star Challenge", "AI4B PRO", "US Holidays"],
    events: [
      { day: "THU 08/06", time: "3:00 PM", title: "AI4B Fail Forward — Patrick Precourt", loc: "Zoom", note: "TODAY" },
      { day: "THU 08/06", time: "6:00 PM", title: "Claude Code Bootcamp — Pre-Installation w/ Kaila", loc: "Zoom 831 5260 7635", note: "TODAY — NEW, added 12:21 AM" },
      { day: "THU 08/06", time: "8:00 PM", title: "Marqus Beaver Business Circle", loc: "Zoom", note: "third event tonight" },
      { day: "SAT 08/08", time: "6:00 PM", title: "ThinkBox AI Intensive Live Training", loc: "Zoom 824 0301 7297", note: "IN 2 DAYS — still duplicated ×2" },
      { day: "MON 08/10", time: "1:00 PM", title: "PRO Welcome Call (duplicate ×2) + Bootcamp 5 PM + Circle 8 PM", loc: "Zoom", note: "heaviest day of the week" },
      { day: "MON–THU", time: "5:00 PM", title: "Vibe Coding Incubator — Claude Code Workshop (Aug 10–13)", loc: "Zoom webinar", note: "pre-work at portal.vcinc.ai first" }
    ]
  },

  notion: {
    openTasks: 0,
    tasksDb: "My Tasks (assigned to me, To-do + In progress)",
    recentPages: [
      { title: "Day 1 — Attendee Notes!", edited: "2026-07-10" },
      { title: "Day 3 — Attendee notes", edited: "2026-07-10" },
      { title: "AI Business Summit Notes and Prompts", edited: "2026-05-15" },
      { title: "Tool Demo Prompts", edited: "2026-05-12" }
    ]
  },

  // Google Drive probe blocked on recent runs — panel shows NO SIGNAL.
  drive: { files: [] },

  canva: {
    designs: [
      { title: "ThinkBox training wall chart (AI integration guide)", updated: "Jul 30" },
      { title: "ELICM Website", updated: "recent" },
      { title: "www.EternalLifeInChristMinistries.org", updated: "recent" },
      { title: "Black White & Yellow Modern Welcome Video", updated: "recent" },
      { title: "Thinkbox A.I. Studios Inc Training", updated: "7 pages" },
      { title: "MJUnlimited AI Animation Package", updated: "6 pages" }
    ]
  },

  slack: {
    workspace: "thinkboxaiope",
    channels: [
      { name: "#all-thinkbox-ai-operating-systems", messages: 0, purpose: "announcements — verified empty today" },
      { name: "#social", messages: 0, purpose: "fun / team bonding" }
    ]
  },

  higgsfield: {
    credits: 437.91,
    plan: "Ultimate"
  }
};
