/* J.A.R.V.I.S. 2 — Infrastructure Brain data (generated by build-brain.mjs)
 * Do not edit by hand if you regenerate — edit the files under sources/ instead.
 * Shape: window.__BRAIN__ = { categories:[{id,label,color}], nodes:[{id,label,cat,note,links:[]}] }
 */
window.__BRAIN__ = {
  "categories": [
    {
      "id": "build",
      "label": "Builds",
      "color": "#34e2e2"
    },
    {
      "id": "client",
      "label": "Clients",
      "color": "#4aa3ff"
    },
    {
      "id": "suite",
      "label": "Skill Suites",
      "color": "#f5c451"
    },
    {
      "id": "project",
      "label": "Projects",
      "color": "#a78bfa"
    },
    {
      "id": "ops",
      "label": "Business Ops",
      "color": "#6ff0c0"
    },
    {
      "id": "note",
      "label": "Notes",
      "color": "#f4a6c0"
    }
  ],
  "nodes": [
    {
      "id": "jarvis2",
      "label": "JARVIS 2 — Core",
      "cat": "build",
      "note": "The assistant itself: brain, sub-agents, memory. Central node.",
      "links": [
        "comms",
        "content",
        "crm",
        "research",
        "memory",
        "gateway"
      ]
    },
    {
      "id": "gateway",
      "label": "OpenClaw Gateway",
      "cat": "build",
      "note": "Control plane: daemon, channels, cron, skills.",
      "links": [
        "telegram",
        "cron"
      ]
    },
    {
      "id": "telegram",
      "label": "Telegram Channel",
      "cat": "build",
      "note": "Front door. Voice + text.",
      "links": []
    },
    {
      "id": "memory",
      "label": "Memory / CRM Store",
      "cat": "build",
      "note": "Supabase long-term memory: people, projects, commitments.",
      "links": [
        "crm"
      ]
    },
    {
      "id": "cron",
      "label": "Cron & Heartbeat",
      "cat": "build",
      "note": "Morning brief + end-of-day wrap.",
      "links": [
        "comms"
      ]
    },
    {
      "id": "brain-ui",
      "label": "Brain UI (3D map)",
      "cat": "build",
      "note": "This visualization on the live Canvas.",
      "links": [
        "crm",
        "jarvis2"
      ]
    },
    {
      "id": "c-brightpath",
      "label": "Client — BrightPath Dental",
      "cat": "client",
      "note": "SEO + Ads retainer. Renewal due Q3. Contact: Dana.",
      "links": [
        "seo",
        "ads",
        "proj-brightpath",
        "p-dana"
      ]
    },
    {
      "id": "c-summit",
      "label": "Client — Summit Fitness",
      "cat": "client",
      "note": "GEO / local map-pack. 3 locations.",
      "links": [
        "geo",
        "proj-summit",
        "p-marco"
      ]
    },
    {
      "id": "c-harbor",
      "label": "Client — Harbor Law",
      "cat": "client",
      "note": "Ads + content. High-value leads.",
      "links": [
        "ads",
        "proj-harbor",
        "p-lena"
      ]
    },
    {
      "id": "c-northside",
      "label": "Client — Northside Cafe",
      "cat": "client",
      "note": "Local GEO + social content.",
      "links": [
        "geo",
        "content",
        "p-omar"
      ]
    },
    {
      "id": "c-verde",
      "label": "Client — Verde Landscaping",
      "cat": "client",
      "note": "Seasonal ads + reviews.",
      "links": [
        "ads",
        "proj-intake"
      ]
    },
    {
      "id": "gmail",
      "label": "Gmail",
      "cat": "ops",
      "note": "Inbox for the comms sub-agent.",
      "links": []
    },
    {
      "id": "gcal",
      "label": "Google Calendar",
      "cat": "ops",
      "note": "Scheduling + conflicts.",
      "links": []
    },
    {
      "id": "drive",
      "label": "Google Drive",
      "cat": "ops",
      "note": "Docs, specs, deliverables.",
      "links": []
    },
    {
      "id": "granola",
      "label": "Granola Notes",
      "cat": "ops",
      "note": "Meeting transcripts.",
      "links": []
    },
    {
      "id": "gamma",
      "label": "Gamma",
      "cat": "ops",
      "note": "AI decks and one-pagers.",
      "links": []
    },
    {
      "id": "canva",
      "label": "Canva",
      "cat": "ops",
      "note": "Branded graphics.",
      "links": []
    },
    {
      "id": "higgs",
      "label": "Higgsfield",
      "cat": "ops",
      "note": "Image / video / audio studio.",
      "links": []
    },
    {
      "id": "vidiq",
      "label": "vidIQ",
      "cat": "ops",
      "note": "YouTube titles + keywords.",
      "links": []
    },
    {
      "id": "jotform",
      "label": "Jotform",
      "cat": "ops",
      "note": "Lead intake forms.",
      "links": [
        "crm"
      ]
    },
    {
      "id": "p-dana",
      "label": "Dana Ruiz",
      "cat": "note",
      "note": "BrightPath decision-maker. Prefers Thursday calls.",
      "links": [
        "c-brightpath"
      ]
    },
    {
      "id": "p-marco",
      "label": "Marco Silva",
      "cat": "note",
      "note": "Summit ops lead.",
      "links": [
        "c-summit"
      ]
    },
    {
      "id": "p-lena",
      "label": "Lena Park",
      "cat": "note",
      "note": "Harbor Law managing partner.",
      "links": [
        "c-harbor"
      ]
    },
    {
      "id": "p-omar",
      "label": "Omar Haddad",
      "cat": "note",
      "note": "Northside owner.",
      "links": [
        "c-northside"
      ]
    },
    {
      "id": "n-rules",
      "label": "Note — Standing Rules",
      "cat": "note",
      "note": "No meetings before 10:00. Fridays heads-down. Flag invoices over $5k.",
      "links": [
        "jarvis2",
        "comms"
      ]
    },
    {
      "id": "n-brand",
      "label": "Note — Brand Voice",
      "cat": "note",
      "note": "Confident, plain, no jargon.",
      "links": [
        "content"
      ]
    },
    {
      "id": "n-pricing",
      "label": "Note — Retainer Pricing",
      "cat": "note",
      "note": "Local $1.5k, Growth $3k, Scale $6k/mo.",
      "links": [
        "ads",
        "seo",
        "geo"
      ]
    },
    {
      "id": "proj-brightpath",
      "label": "Project — BrightPath Q3",
      "cat": "project",
      "note": "Renewal + expanded ad budget. At risk: waiting on creative approval.",
      "links": [
        "content"
      ]
    },
    {
      "id": "proj-summit",
      "label": "Project — Summit Local Launch",
      "cat": "project",
      "note": "New location GEO rollout. On track.",
      "links": [
        "geo"
      ]
    },
    {
      "id": "proj-harbor",
      "label": "Project — Harbor Lead Gen",
      "cat": "project",
      "note": "Landing pages + paid search.",
      "links": [
        "ads"
      ]
    },
    {
      "id": "proj-intake",
      "label": "Project — Client Intake System",
      "cat": "project",
      "note": "Jotform to CRM automation for new leads.",
      "links": [
        "jotform",
        "crm"
      ]
    },
    {
      "id": "comms",
      "label": "Comms Sub-agent",
      "cat": "suite",
      "note": "Email + calendar. Triage, draft, schedule.",
      "links": [
        "gmail",
        "gcal"
      ]
    },
    {
      "id": "content",
      "label": "Content Studio",
      "cat": "suite",
      "note": "Decks, design, media, YouTube growth.",
      "links": [
        "gamma",
        "canva",
        "higgs",
        "vidiq"
      ]
    },
    {
      "id": "crm",
      "label": "CRM & Memory",
      "cat": "suite",
      "note": "Remember/recall clients, projects, commitments.",
      "links": [
        "memory"
      ]
    },
    {
      "id": "research",
      "label": "Research Sub-agent",
      "cat": "suite",
      "note": "Web + Drive + meeting transcripts, verified.",
      "links": [
        "drive",
        "granola"
      ]
    },
    {
      "id": "seo",
      "label": "SEO Suite",
      "cat": "suite",
      "note": "Organic search playbooks and audits.",
      "links": [
        "content"
      ]
    },
    {
      "id": "geo",
      "label": "GEO Suite",
      "cat": "suite",
      "note": "Local / map-pack visibility.",
      "links": [
        "content"
      ]
    },
    {
      "id": "ads",
      "label": "Ads Suite",
      "cat": "suite",
      "note": "Paid acquisition, search & social.",
      "links": [
        "content"
      ]
    }
  ]
};
