#!/usr/bin/env node
/* J.A.R.V.I.S. 2 — Brain graph builder
 * ----------------------------------------------------------------------------
 * Turns your business records into the graph that the 3D brain renders.
 * Reads every *.json file in ./sources/ and writes ./brain-data.js.
 *
 *   node jarvis/brain/build-brain.mjs
 *
 * Each source file is an ARRAY of records:
 *   { "id": "client-brightpath",
 *     "label": "Client — BrightPath Dental",
 *     "cat": "client",              // build | client | suite | project | ops | note
 *     "note": "SEO + Ads retainer. Renewal Q3.",
 *     "links": ["seo","ads"] }      // ids of related records (edges are bidirectional)
 *
 * Where does the data come from? Two easy paths:
 *   1. Export from JARVIS's CRM (Supabase) — one JSON array per table (people,
 *      projects, commitments) mapped to the shape above.
 *   2. Hand-maintain a few JSON files under sources/ (clients.json, builds.json…).
 *
 * JARVIS can regenerate this for you: "update the brain" → the jarvis-brain skill
 * pulls the CRM, writes sources/, and runs this script.
 * ---------------------------------------------------------------------------- */
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "sources");
const OUT = join(HERE, "brain-data.js");

const CATEGORIES = [
  { id: "build",   label: "Builds",       color: "#34e2e2" },
  { id: "client",  label: "Clients",      color: "#4aa3ff" },
  { id: "suite",   label: "Skill Suites", color: "#f5c451" },
  { id: "project", label: "Projects",     color: "#a78bfa" },
  { id: "ops",     label: "Business Ops", color: "#6ff0c0" },
  { id: "note",    label: "Notes",        color: "#f4a6c0" },
];
const VALID = new Set(CATEGORIES.map((c) => c.id));

async function loadSources() {
  let files = [];
  try {
    files = (await readdir(SRC)).filter((f) => f.endsWith(".json"));
  } catch {
    console.error(`No sources/ directory found at ${SRC}.`);
    console.error("Create it with JSON arrays of records, or edit brain-data.js by hand.");
    process.exit(1);
  }
  const records = [];
  for (const f of files) {
    const raw = await readFile(join(SRC, f), "utf8");
    let arr;
    try { arr = JSON.parse(raw); } catch (e) {
      console.error(`Skipping ${f}: invalid JSON (${e.message})`); continue;
    }
    if (!Array.isArray(arr)) { console.error(`Skipping ${f}: expected a JSON array`); continue; }
    for (const r of arr) records.push({ ...r, _src: f });
  }
  return records;
}

function normalize(records) {
  const seen = new Map();
  for (const r of records) {
    if (!r.id || !r.label) { console.error(`Skipping record without id/label in ${r._src}`); continue; }
    if (!VALID.has(r.cat)) { console.error(`Record ${r.id}: unknown cat "${r.cat}" — defaulting to "note"`); r.cat = "note"; }
    const node = {
      id: String(r.id),
      label: String(r.label),
      cat: r.cat,
      note: r.note ? String(r.note) : "",
      links: Array.isArray(r.links) ? r.links.map(String) : [],
    };
    seen.set(node.id, node); // last write wins on duplicate id
  }
  const nodes = [...seen.values()];
  // drop links that point to missing nodes
  const ids = new Set(nodes.map((n) => n.id));
  for (const n of nodes) n.links = n.links.filter((t) => ids.has(t) && t !== n.id);
  return nodes;
}

const banner =
`/* J.A.R.V.I.S. 2 — Infrastructure Brain data (generated by build-brain.mjs)
 * Do not edit by hand if you regenerate — edit the files under sources/ instead.
 * Shape: window.__BRAIN__ = { categories:[{id,label,color}], nodes:[{id,label,cat,note,links:[]}] }
 */\n`;

const nodes = normalize(await loadSources());
if (!nodes.length) { console.error("No valid records found. Nothing written."); process.exit(1); }

const payload = { categories: CATEGORIES, nodes };
await writeFile(OUT, banner + "window.__BRAIN__ = " + JSON.stringify(payload, null, 2) + ";\n", "utf8");

const counts = nodes.reduce((a, n) => ((a[n.cat] = (a[n.cat] || 0) + 1), a), {});
const edges = nodes.reduce((a, n) => a + n.links.length, 0);
console.log(`Wrote ${OUT}`);
console.log(`  ${nodes.length} nodes · ~${edges} links`);
console.log("  " + Object.entries(counts).map(([k, v]) => `${k}:${v}`).join("  "));
